apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-backend
spec:
  selector:
    matchLabels:
      app: eshop-backend
  template:
    metadata:
      labels:
        app: eshop-backend
    spec:
      containers:
        - name: eshop-backend
          image: eshop-backend
          ports:
          - containerPort: 8090
          env:
            - name: URL_CARTSERVICE
              value: http://eshop-cartservice:8091
            - name: URL_PRODUCTSERVICE
              value: http://eshop-productservice:8092
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/eshop_db"
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: OPENTRACING_JAEGER_HTTP-SENDER_URL
              value: "http://jaeger-collector.istio-system.svc.cluster.local:14268/api/traces"         
---
apiVersion: v1
kind: Service
metadata:
  name: eshop-backend
spec:
  type: ClusterIP
  selector:
    app: eshop-backend
  ports:
  - port: 8090