apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-currencyservice
spec:
  selector:
    matchLabels:
      app: eshop-currencyservice
  template:
    metadata:
      labels:
        app: eshop-currencyservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: eshop-currencyservice
        image: eshop-currencyservice
        ports:
        - containerPort: 8094
        env:
        - name: PORT
          value: "8094"
        - name: JAEGER_ENDPOINT
          value: "http://jaeger-collector.istio-system.svc.cluster.local:14268/api/traces"
---
apiVersion: v1
kind: Service
metadata:
  name: eshop-currencyservice
spec:
  type: ClusterIP
  selector:
    app: eshop-currencyservice
  ports:
  - name: api
    port: 8094
    targetPort: 8094